#ifndef HADRONS_ME_Library_HeavyBaryon_SimpleTwoBody_Decay_MEs_H
#define HADRONS_ME_Library_HeavyBaryon_SimpleTwoBody_Decay_MEs_H

#include "HADRONS++/ME_Library/HD_ME_Base.H"

namespace HADRONS {
  /*! \file HeavyBaryon_SimpleTwoBody_Decay_MEs.H
    In principle, most of the decay amplitudes are similar to the ones in 
    Baryon_SimpleDecay_MEs.H, so this here is about fixing constants - nevertheless,
    there may be some differences.  

    We should try to implement hep-ph/9612223, hep-ph/0006109 and hep-ph/0312160 here.
    For charmed baryons, we should take Z.Phys.C55 659, hep-ph/9603426, hep-ph/9504428,
    and hep-ph/9406359.  For one-pion and one-photon decays, we should do hep-ph/9904421
  */
};

