@node Command line
@chapter Command line options 

The available command line options for Sherpa.

@table @option

@item -f <file>
Read input from file @samp{<file>}.

@item -p <path>
Read input file from path @samp{<path>}.

@item -L <path>
Set Sherpa library path to @samp{<path>},
see @ref{SHERPA_CPP_PATH}.

@item -e <events>
Set number of events to generate @samp{<events>},
see @ref{EVENTS}.

@item -t <events>
Set the event type to @samp{<events>},
see @ref{EVENT_TYPE}.

@item -r <results>
Set the result directory to @samp{<results>},
see @ref{RESULT_DIRECTORY}.

@item -R <seed>
Set the seed of the random number generator to @samp{<seed>},
see @ref{RANDOM_SEED}.

@item -m <generators>
Set the matrix element generator list to @samp{<generators>},
see @ref{ME_SIGNAL_GENERATOR}.

@item -w <mode>
Set the event generation mode to @samp{<mode>},
see @ref{EVENT_GENERATION_MODE}.

@item -s <generator>
Set the parton shower generator to @samp{<generator>},
see @ref{SHOWER_GENERATOR}.

@item -F <module>
Set the fragmentation module to @samp{<module>},
see @ref{Fragmentation}.

@item -D <module>
Set the hadron decay module to @samp{<module>},
see @ref{Hadron decays}.

@item -a <analyses>
Set the analysis handler list to @samp{<analyses>},
see @ref{ANALYSIS}.

@item -A <path>
Set the analysis output path to @samp{<path>},
see @ref{ANALYSIS_OUTPUT}.

@item -O <level>
Set general output level @samp{<level>}, see @ref{OUTPUT}.

@item -o <level>
Set output level for event generation @samp{<level>}, see @ref{OUTPUT}.

@item -l <logfile>
Set log file name @samp{<logfile>}, see @ref{LOG_FILE}.

@item -j <threads>
Set number of threads @samp{<threads>}, see @ref{Multi-threading}.

@item -g
Do not create result directory, see @ref{RESULT_DIRECTORY}.

@item -b
Switch to non-batch mode, see @ref{BATCH_MODE}.

@item -V
Print extended version information at startup.

@item -v, --version
Print versioning information.

@item -h, --help
Print a help message.

@item PARAMETER=VALUE
Set the value of a parameter, see @ref{Parameters}.

@item TAG:=VALUE
Set the value of a tag, see @ref{Tags}.

@end table

