@node Events
@subsection Generate events using scripts

This example shows how to generate events with Sherpa
using a Python wrapper script. For each event the weight,
the number of trials and the particle information is printed
to stdout. This script can be used as a basis for constructing
interfaces to own analysis routines.

@example
@smallformat
@verbatiminclude Examples/API/Events/test.py.in
@end smallformat
@end example
