@node Hard decays
@section Hard decays
@cindex HARD_DECAYS
@cindex STABLE[<id>]

The handler for decays of particles produced in the hard scattering process
(e.g. W, Z, top, Higgs) can be enabled using the @option{HARD_DECAYS=1} switch.
Which (anti)particles should be treated as unstable is determined by the
@option{STABLE[<id>]} switch described in @ref{Model Parameters}.

This decay module can also be used on top of NLO matrix elements, but it does
not include any NLO corrections in the decay matrix elements themselves.

Note that the decay handler is an afterburner at the event generation level.
It does not affect the calculation and integration of the hard scattering
matrix elements. The cross section is thus unaffected during integration, and
the branching ratios (if any decay channels have been disabled) are only taken
into account for the event weights and cross section output at the end of event
generation (if not disabled with the @option{HDH_BR_WEIGHTS} option, cf. below).
Furthermore any cuts or scale definitions are not affected by decays
and operate only on the inclusively produced particles before decays.

@menu
* HDH_NO_DECAY::
* HDH_ONLY_DECAY::
* HARD_SPIN_CORRELATIONS::
* STORE_DECAY_RESULTS::
* DECAY_RESULT_DIRECTORY::
* HDH_SET_WIDTHS::
* HDH_BR_WEIGHTS::
* HARD_MASS_SMEARING::
* RESOLVE_DECAYS::
* DECAY_TAU_HARD::
@end menu

@node HDH_NO_DECAY
@subsection HDH_NO_DECAY
@cindex HDH_NO_DECAY

This option allows to disable an explicit list of decay channels. For example,
to disable the hadronic decay channels of the W boson one would use:
@verbatim
HDH_NO_DECAY={24,2,-1}|{24,4,-3}|{-24,-2,1}|{-24,-4,3}
@end verbatim
Note that the ordering of the decay products in each channel is important and
has to be identical to the ordering in the decay table printed to screen.
Multiple decay channels (also for different decaying particles and
antiparticles) can be specified using the @option{|} (pipe) symbol as separator.
Spaces are not allowed anywere in the list.

@node HDH_ONLY_DECAY
@subsection HDH_ONLY_DECAY
@cindex HDH_ONLY_DECAY

This option allows to restrict the decay channels of a particle to the
explicitly given list. For example, to allow only the bottom-decay mode of the
Higgs one would use
@verbatim
HDH_ONLY_DECAY={25,5,-5}
@end verbatim
Note that the ordering of the decay products in each channel is important and
has to be identical to the ordering in the decay table printed to screen.
Multiple decay channels (also for different decaying particles and
antiparticles) can be specified using the @option{|} (pipe) symbol as separator.
Spaces are not allowed anywere in the list.

@node HARD_SPIN_CORRELATIONS
@subsection HARD_SPIN_CORRELATIONS
@cindex HARD_SPIN_CORRELATIONS

By default, all decays are done in a factorised manner, i.e. there are no
correlations between the production and decay matrix elements of an unstable
particle. It is possible to enable spin correlations by specifying
@option{HARD_SPIN_CORRELATIONS=1}, which might come with a small performance
penalty in more complicated processes.

@node STORE_DECAY_RESULTS
@subsection STORE_DECAY_RESULTS
@cindex STORE_DECAY_RESULTS

The decay table and partial widths are calculated on-the-fly during the
initialization phase of Sherpa from the given model and its particles and
interaction vertices. To store these results in the @code{Results/Decays}
directory, one has to specify @option{STORE_DECAY_RESULTS=1}. In case
existing decay tables are to be read in @option{STORE_DECAY_RESULTS=1}
is to be specified as well. Please note, that Sherpa will delete decay
channels present in the read in results but not in the present model with
present parameters by default. To prevent Sherpa from updating the
decay table files accordingly specify @option{STORE_DECAY_RESULTS=2}.

@node DECAY_RESULT_DIRECTORY
@subsection DECAY_RESULT_DIRECTORY
@cindex DECAY_RESULT_DIRECTORY

Specifies the name of the directory where the decay results are to be 
stored. Defaults to the value of @ref{RESULT_DIRECTORY}.

@node HDH_SET_WIDTHS
@subsection HDH_SET_WIDTHS
@cindex HDH_SET_WIDTHS
@cindex WIDTH[<id>]

The decay handler computes LO partial and total decay widths and generates
decays with corresponding branching fractions, independently from the particle
widths specified by @option{WIDTH[<id>]}. The latter are relevant only for the
core process and should be set to zero for all unstable particles appearing
in the core-process final state. This guarantees on-shellness and gauge
invariance of the core process, and subsequent decays can be handled by the
afterburner.
In constrast, @option{WIDTH[<id>]} should be set to the physical width when unstable
particles appear (only) as intermediate states in the core process, i.e. when
production and decay are handled as a full process or using
@code{Decay}/@code{DecayOS}.
In this case, the option @option{HDH_SET_WIDTHS=1} permits to overwrite the
@option{WIDTH[<id>]} values of unstable particles by the LO widths computed by
the decay handler.

@node HDH_BR_WEIGHTS
@subsection HDH_BR_WEIGHTS
@cindex HDH_BR_WEIGHTS

By default (@option{HDH_BR_WEIGHTS=1}), weights for events which involve a hard
decay are multiplied with the corresponding branching ratios (if decay channels
have been disabled). This also means that the total cross section at the end of
the event generation run already includes the appropriate BR factors. If you
want to disable that, e.g. because you want to multiply with your own modified
BR, you can set the option @option{HDH_BR_WEIGHTS=0}.


@node HARD_MASS_SMEARING
@subsection HARD_MASS_SMEARING
@cindex HARD_MASS_SMEARING

If @option{HARD_MASS_SMEARING=1} is specified, the kinematic mass of the unstable
propagator is distributed according to a Breit-Wigner shape a posteriori. All
matrix elements are still calculated in the narrow-width approximation with
onshell particles. Only the kinematics are affected.

@node RESOLVE_DECAYS
@subsection RESOLVE_DECAYS
@cindex RESOLVE_DECAYS

There are different options how to decide when a 1->2 process should be replaced
by the respective 1->3 processes built from its decaying daughter particles.

@table @option
@item RESOLVE_DECAYS=Threshold
(default)
Only when the sum of decay product masses exceeds the decayer mass.
@item RESOLVE_DECAYS=ByWidth
As soon as the sum of 1->3 partial widths exceeds the 1->2 partial width.
@item RESOLVE_DECAYS=None
No 1->3 decays are taken into account.
@end table

@node DECAY_TAU_HARD
@subsection DECAY_TAU_HARD
@cindex DECAY_TAU_HARD

By default, the tau lepton is decayed by the hadron decay module,
@ref{Hadron decays}, which includes not only the leptonic decay channels but
also the hadronic modes. If @option{DECAY_TAU_HARD=1} is specified, the tau
lepton will be decayed in the hard decay handler, which only takes leptonic and
partonic decay modes into account. Note, that in this case the tau needs to also
be set massive with @option{MASSIVE[15]=1}.
