@node HERA
@subsection DIS at HERA

This is an example of a setup for hadronic final states in deep-inelastic 
lepton-nucleon scattering at a centre-of-mass energy of 300 GeV.
Corresponding measurements were carried out by the H1 and ZEUS collaborations
at the HERA collider at DESY Hamburg.

@example
@smallformat
@verbatiminclude Examples/Jets_in_DIS/HERA/Run.dat
@end smallformat
@end example
 
Things to notice:
@itemize @bullet
@item the beams are asymmetric with the positrons at an energy of 27.6 GeV,
while the protons carry 820 GeV of energy.

@item the multi-jet merging cut is set dynamically for each event, depending 
on the photon virtuality, see @mycite{Carli2009cg}.

@item there is a selector cut on the photon virtuality. This cut implements
the experimental requirements for idenitfying the deep-inelastic scattering process.

@end itemize
