@node Top quark pair production
@subsection Top quark pair production

@example
@smallformat
@verbatiminclude Examples/Tops_plus_Jets/LHC_Tops/Run.dat
@end smallformat
@end example

Things to notice:
@itemize
@item We use OpenLoops to compute the virtual corrections @mycite{Cascioli2011va}.
@item We match matrix elements and parton showers using the MC@@NLO technique 
for massive particles, as described in @mycite{Hoeche2013mua}.
@item A non-default METS core scale setter is used, cf. @ref{METS scale setting with multiparton core processes}
@item We enable top decays through the internal decay module using @option{HARD_DECAYS 1}
@end itemize
