@iftex 
@macro Sherpa{}
S\scalebox{0.8}{HERPA}\xspace 
@end macro
@end iftex 
@ifnottex
@macro Sherpa{}
Sherpa 
@end macro
@end ifnottex
@iftex 
@macro Amegic{}
A\scalebox{0.8}{MEGIC++}\xspace 
@end macro
@end iftex 
@ifnottex
@macro Amegic{}
AMEGIC++ 
@end macro
@end ifnottex 
@iftex 
@macro Photons{}
P\scalebox{0.8}{HOTONS++}\xspace
@end macro
@end iftex 
@ifnottex
@macro Photons{}
PHOTONS++
@end macro
@end ifnottex

@set spires http://inspirehep.net/search?p=

@macro mybibmake{llink,lref}
@end macro

@ifinfo
@macro mycite{ref}
[@value{K\ref\}] in @ref{References} @set U\ref\ true
@end macro
@end ifinfo
@ifnotinfo
@macro mycite{ref}
@set U\ref\ true
[@ref{\ref\, @value{K\ref\}}]
@end macro
@end ifnotinfo

@macro mybibitem{ref,key,author,title,journal,vol,year,pages,eprint,slink}
@ifclear mybibout
@set K\ref\ \key\
@clear U\ref\
@end ifclear
@ifset U\ref\
@item
@ifinfo
@anchor{\ref\}[\key\] 
@end ifinfo
@ifnotinfo
@anchor{\ref\}[@uref{@value{spires}\slink\,\key\}] 
@end ifnotinfo
\author\, @emph{\title\}, \journal\ @b{\vol\} \year\ \pages\ \eprint\.
@ifinfo
@sp 1
@end ifinfo
@ifnotinfo
@sp 2
@end ifnotinfo
@end ifset
@end macro

@macro mybibbegin{filename}
@include \filename\
@end macro

@macro mybibend{filename}
@node References
@appendix References
@itemize @asis
@set mybibout true
@include \filename\
@end itemize
@end macro
