@node MPI Parameters
@section Multiple interactions

The multiple parton interaction (MPI) setup is covered by
the `(mi)' section of the steering file or the
MPI data file `MI.dat', respectively. The basic MPI model is described
in @mycite{Sjostrand1987su} while Sherpa's implementation details are
discussed in @mycite{Alekhin2005dx}

The following parameters are used to steer the MPI setup.

@menu
* MI_HANDLER::          The MPI handler
* TURNOFF::             The p_T turnoff
* SCALE_MIN::           The p_T cutoff
* PROFILE_FUNCTION::    The hadron profile function
* PROFILE_PARAMETERS::  The hadron profile function
* REFERENCE_SCALE::     The reference scale
* RESCALE_EXPONENT::    The rescaling exponent
* TURNOFF_EXPONENT::    The rescaling exponent for the turnoff
* SIGMA_ND_FACTOR::     The non-diffractive cross section factor
* MI_RESULT_DIRECTORY:: The directory for the MPI grid
* MI_RESULT_DIRECTORY_SUFFIX:: The suffix for the directory for the MPI grid
@end menu


@node MI_HANDLER
@subsection MI_HANDLER
@cindex MI_HANDLER
Specifies the MPI handler. The two possible values
at the moment are @option{None} and @option{Amisic}.


@node TURNOFF
@subsection TURNOFF
@cindex TURNOFF
Specifies the transverse momentum turnoff in GeV.

@node SCALE_MIN
@subsection SCALE_MIN
@cindex SCALE_MIN
Specifies the transverse momentum integration cutoff in GeV.


@node PROFILE_FUNCTION
@subsection PROFILE_FUNCTION
@cindex PROFILE_FUNCTION
Specifies the hadron profile function. The possible values are
@option{Exponential}, @option{Gaussian} and @option{Double_Gaussian}.
For the double gaussian profile, the relative core size and relative
matter fraction can be set using @ref{PROFILE_PARAMETERS}.

@node PROFILE_PARAMETERS
@subsection PROFILE_PARAMETERS
@cindex PROFILE_PARAMETERS
The potential parameters for hadron profile functions, see 
@ref{PROFILE_FUNCTION}. For double gaussian profiles there are
two parameters, corresponding to the relative core size and relative
matter fraction.

@node REFERENCE_SCALE
@subsection REFERENCE_SCALE
@cindex REFERENCE_SCALE
Specifies the centre-of-mass energy at which the transverse momentum
integration cutoff is used as is, see @ref{SCALE_MIN}. 
This parameter should not be changed by the user. The default is
@samp{1800}, corresponding to Tevatron Run I energies.

@node RESCALE_EXPONENT
@subsection RESCALE_EXPONENT
@cindex RESCALE_EXPONENT
Specifies the rescaling exponent for fixing the transverse momentum
integration cutoff at centre-of-mass energies different from the
reference scale, see @ref{SCALE_MIN}, @ref{REFERENCE_SCALE}.

@node TURNOFF_EXPONENT
@subsection TURNOFF_EXPONENT
@cindex TURNOFF_EXPONENT
Specifies the rescaling exponent for fixing the transverse momentum
turnoff at centre-of-mass energies different from the
reference scale, see @ref{TURNOFF}, @ref{REFERENCE_SCALE}.

@node SIGMA_ND_FACTOR
@subsection SIGMA_ND_FACTOR
@cindex SIGMA_ND_FACTOR
Specifies the factor to scale the non-diffractive cross section 
calculated in the MPI initialisation.

@node MI_RESULT_DIRECTORY
@subsection MI_RESULT_DIRECTORY
@cindex MI_RESULT_DIRECTORY
Specifies the name of the directory where the MPI grid is stored. The 
default comprises the beam particles, their energies and the PDF used. 
In its default value, this information safeguards against using unsuitable 
grids for the current calculation, assuming a standard @ref{TUNE} has 
been used.

@node MI_RESULT_DIRECTORY_SUFFIX
@subsection MI_RESULT_DIRECTORY_SUFFIX
@cindex MI_RESULT_DIRECTORY_SUFFIX
Supplements the default directory name for the MPI grid with a suffix.
