@node Models
@section Models
@cindex MODEL

The main switch @code{MODEL} in the @code{(run)@{...@}(run)} section of
the run card sets the model that Sherpa uses throughout the simulation
run. The default is @option{SM}, the built-in Standard Model
implementation of Sherpa. For BSM simulations, Sherpa offers an option
to use the Universal FeynRules Output Format (UFO)
@mycite{Degrande2011ua}.

Please note: AMEGIC can only be used for the built-in models (SM and
HEFT). For anything else, please use Comix.

@menu
* Built-in Models::    SM and Higgs Effective Theory
* UFO Model Interface::Generic Interface for BSM models in the UFO format
@end menu

@node Built-in Models
@subsection Built-in Models

@menu
* SM::  Standard Model
* HEFT::Higgs Effective Coupling
@end menu

@include SM.texi
@include HEFT.texi

@node UFO Model Interface
@subsection UFO Model Interface
@cindex UFO_PARAM_CARD

@include UFO.texi
