@node Parameters
@chapter Parameters

A Sherpa setup is steered by various parameters, associated with the
different components of event generation. These are set in 
@iftex 
S\scalebox{0.8}{HERPA}\xspace's 
@end iftex 
@ifnottex
Sherpa's
@end ifnottex 
run-card, see @ref{Input structure} for more details. Tag replacements may be
performed in all inputs, see @ref{Tags}.

@menu
* Run Parameters::    List of general parameters
* Beam Parameters::   List of beam parameters
* ISR Parameters::    List of initial state radiation parameters
* Model Parameters::  List of interaction model parameters
* Matrix Elements::   Matrix element related settings
* Processes::         Syntax of the process setup
* Selectors::         Syntax of parton level cuts
* Integration::       List of integration parameters
* Hard decays::       List of paramters to steer hard/inclusive decays
* Shower Parameters:: List of shower parameters
* MPI Parameters::    List of multiple parton interaction parameters
* Hadronization::     List of hadronization parameters
* QED Corrections::   List of QED correction parameters
* Minimum Bias::      List of minimum bias simulation parameters
@end menu

@include Run.texi
@include Beam.texi
@include ISR.texi
@include Model.texi
@include ME.texi
@include Processes.texi
@include Selector.texi
@include Integration.texi
@include HardDecays.texi
@include Shower.texi
@include MI.texi
@include Fragmentation.texi
@include SoftQED.texi
@include MinBias.texi

