@node SM
@subsection Standard Model
@cindex 1/ALPHAQED(0)
@cindex SIN2THETAW
@cindex VEV
@cindex LAMBDA
@cindex EW_SCHEME
@cindex CKMORDER
@cindex CABIBBO
@cindex A
@cindex ETA
@cindex RHO
@cindex ALPHAS(MZ)
@cindex 1/ALPHAQED(default)
@cindex ALPHAS(default)
@cindex ORDER_ALPHAS
@cindex USE_PDF_ALPHAS
@cindex WIDTH_SCHEME


The SM inputs for the electroweak sector can be given in four different 
schemes, that correspond to different choices of which SM physics 
parameters are considered fixed and which are derived from the given 
quantities. The input schemes are selected through the @code{EW_SCHEME} 
parameter, whose default is @option{1}. The following options are provided:
@itemize @bullet
  @item  Case @code{0}:
  
    all EW parameters are explicitly given.
    Here the W, Z and Higgs masses are taken as inputs, and
    the parameters @code{1/ALPHAQED(default)}, @code{SIN2THETAW}, @code{VEV}
    and @code{LAMBDA} have to be specified as well. While 
    @code{1/ALPHAQED(default)} corresponds to the fine structure constant,
    (which by default is not running), the parameters @code{SIN2THETAW}, 
    @code{VEV}, and @code{LAMBDA} thereby specify the weak mixing angle,
    the Higgs field vacuum expectation value, and the Higgs quartic
    coupling respectively.

    Note that this mode allows to violate the tree-level relations between
    some of the parameters and can thus not be used with the complex mass
    scheme (cf. below).
  @item  Case @code{1}:
  
    all EW parameters are calculated out of the W, Z and Higgs masses and
    @code{1/ALPHAQED(default)} using tree-level relations.
  @item  Case @code{2}:
  
    all EW parameters are calculated out of @code{1/ALPHAQED(default)}, 
    @code{SIN2THETAW}, @code{VEV} and the Higgs mass using tree-level relations.

    Note that this mode can not be used with the complex mass scheme
    (cf. below).
  @item  Case @code{3}:
  
    this choice corresponds to the G_mu-scheme. The EW parameters are 
    calculated out of the weak gauge boson masses M_W, M_Z, the Higgs
    boson mass M_H and the Fermi constant @code{GF} using tree-level relations.
  @end itemize

The electro-weak coupling is by default not running. If its running has been
enabled (cf. @ref{COUPLINGS}), one can specify its value at zero momentum
transfer as input value by @code{1/ALPHAQED(0)}.

To account for quark mixing the CKM matrix elements have to be assigned. 
For this purpose the Wolfenstein parametrization @mycite{Wolfenstein1983yz} is
employed. The order of expansion in the lambda parameter is defined
through @code{CKMORDER}, with default @option{0} corresponding to a unit matrix.
The parameter convention for higher expansion terms reads:

@itemize @bullet
@item  @code{CKMORDER = 1}, the @code{CABIBBO} parameter has to be set,
it parametrizes lambda and has the default value @option{0.2272}.
@item  @code{CKMORDER = 2}, in addition the value of @code{A} has to
be set, its default is @option{0.818}. 
@item  @code{CKMORDER = 3}, the order lambda^3 expansion, @code{ETA}
and @code{RHO} have to be specified. Their default values are @option{0.349} 
and @option{0.227}, respectively.
@end itemize


The remaining parameter to fully specify the Standard Model 
is the strong coupling constant at the Z-pole, given through
@code{ALPHAS(MZ)}. Its default value is @option{0.118}. If the setup
at hand involves hadron collisions and thus PDFs, the value of the
strong coupling constant is automatically set consistent with the PDF fit
and can not be changed by the user. If Sherpa is compiled with LHAPDF
support, it is also possible to use the alphaS evolution provided
in LHAPDF by specifying @code{USE_PDF_ALPHAS=1}.
For this fine structure constant there is also the option to provide
a fixed value that can be used in calculations of matrix elements
in case running of the coupling is disabled (cf. @ref{COUPLINGS}). The keyword
is @code{ALPHAS(default)}. When using
a running strong coupling, the order of the perturbative expansion 
used can be set through @code{ORDER_ALPHAS}, where the default @option{0}
corresponds to one-loop running and @code{1},@code{2},@code{3} 
to 2,3,4-loops, respectively.  

If unstable particles (e.g. W/Z bosons) appear as intermediate propagators
in the process, Sherpa uses the complex mass scheme to construct MEs
in a gauge-invariant way. For full consistency with this scheme,
by default the dependent EW parameters are also calculated from the complex
masses (@option{WIDTHSCHEME=CMS}), yielding complex values e.g. for
the weak mixing angle.
To keep the parameters real one can set @option{WIDTHSCHEME=Fixed}. This may
spoil gauge invariance though.
