@node THDM
@subsection Two Higgs Doublet Model
@cindex TAN(BETA)
@cindex ALPHA

The THDM is incorporated as a subset of the MSSM Lagrangian. It is
defined as the extension of the SM by a second SU(2) doublet of
Higgs fields. Besides the particle content of the SM it contains
interactions of five physical Higgs bosons: a light and a heavy
scalar, a pseudo-scalar and two charged ones. Besides the SM inputs
the model is defined through the masses and widths of the Higgs
particles, @code{MASS[PDG]} and @code{WIDTH[PDG]}, where PDG = [25,35,36,37] for
h^0, H^0, A^0 and H^+, respectively. The inputs are complete, when
TAN(BETA), the ratio of the two Higgs vacuum expectation values,
and ALPHA, the Higgs mixing angle, are specified.

The model is invoked by specifying @code{MODEL = THDM} in the @code{(model)}
section of the steering file or the model data file @code{Model.dat},
respectively.
